query getNotes($slug: String) {
	notes(where: { Slug: $slug }) {
		id
		title
		Slug
		content
		author {
	    	username
		}
		published_date
		Featured_Img {
	    	url
		}
		note_tr {
			rowTitle
			perfromanceScore
			accessibility
			bestPractices
			seo
			mobileScore
			desktopScore
			client_category {
				name
			}
		    hostingOnly
		}
		Public
	}
}
